### PR TITLE
Fix nat_gateway_enabled=false InvalidNatGatewayId.Malformed error 

### LINKED ISSUE #44: Setting the nat_gateway_enabled=false results in Invalid index error
## Describe the Bug
Setting the nat_gateway_enabled=false results in InvalidNatGatewayId.Malformed error on private subnets aws_route resource

## Expected Behavior
Terraform apply should run without error and no routes to the nat gateways should exist in the private subnets

## Steps to Reproduce
1. Go to examples/complete/main.tf
2. Edit `nat_gateway_enabled = true` to be `nat_gateway_enabled = false`
3. Run `terraform apply -var-file fixtures.us-east-2.tfvars`
4. See error `InvalidNatGatewayId.Malformed: Invalid id: "0" (expecting "nat-...")`

## Screenshots
Not necessary

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS:Linux
 - TF Version 14.7

## Additional Context
None

### PR DESCRIPTION
**Pull request by paulrob-100**
## what

* Fix #44 
* Error reported is 'InvalidNatGatewayId.Malformed: Invalid id: "0" (expecting "nat-...")'
* Make nat_gateway_enabled variable type explicit boolean
* Remove dummy_az_ngw_ids and return empty map when disabled, which means private.tf nat_gateways_route_count is not dependent on the results of the apply
  * Tried using a local list with conditional comparison to the "0" constant but then dependent on the results of the apply
* Added new fixture in eu-west-1 region and new test
* terraform get -update fails when running tests in parallel hence disabled
* Tested route tables with nat_gateway_enabled flag disabled and enabled (tests would need an extra output to test in code)

## why
* Users should be able to create subnets without NAT gateways 

## references
* closes #44

### CODE REVIEW

**Review by Gowiem — COMMENTED** [review]
@paulrob-100 this looks good to me and you obviously put a good bit of work into it so thank you. I'm going to call in a 2nd reviewer here since this isn't a trivial change. @Nuru you mind taking a look at this when you get the chance?

**Comment by paulrob-100** [comment]
Thanks @Gowiem. I'm looking at the failing test to see if I can reproduce.

```
--- FAIL: TestExamplesCompleteNoNatGateway (48.00s)
    destroy.go:11: 
        	Error Trace:	destroy.go:11
        	            				examples_complete_test.go:126
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: Invalid count argument
        	            	
        	            	  on ../../private.tf line 96, in resource "aws_route" "default":
        	            	  96:   count = local.nat_gateways_route_count
```

**Comment by paulrob-100** [comment]
I'm not able to reproduce the failing test locally @Gowiem. 
I'm using 0.14.7, but there is some logic in the build harness which is selecting 0.13.6.
The test itself is passing, but then the destroy fails with the error. Perhaps a terraform bug?
Any ideas how to fix?

**Comment by paulrob-100** [comment]
Design note:-
The local nat_gw_availability_zones_map introduced in public.tf will conflict with the alternative list of tuple implementation introduced in #47 
https://github.com/cloudposse/terraform-aws-multi-az-subnets/pull/45/files#diff-cc32539d62c7383a06d2f5a9a3e22fdc92a499303657ead4f0ddda0eeb82516dR132

I think I prefer #47 implementation which means this local disappears in the merge.

**Comment by nitrocode** [comment]
```
Error: Invalid count argument

  on ../../private.tf line 96, in resource "aws_route" "default":
  96:   count = local.nat_gateways_route_count

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

It looks like the example that it's trying to apply depends on `module.public_subnets.az_ngw_ids` for the `az_ngw_ids` input which turns into 

https://github.com/cloudposse/terraform-aws-multi-az-subnets/blob/5e04ef2c18974152f448857fac3dc894b5a71f35/examples/complete/main.tf#L32-L41

Perhaps a `depends_on` argument would be good enough to add to `module "private_subnets"` ?

```hcl
  depends_on = [module.public_subnets]
```

That should hopefully allow `module.public_subnets` to fully finish prior to applying `module.private_subnets`

**Comment by paulrob-100** [comment]
Thanks for your investigation @nitrocode.
I've found a number of similar issues reported in the terraform repo.
This one seems similar and wasn't fixed in the 0.13 series.
https://github.com/hashicorp/terraform/issues/26078

**Comment by paulrob-100** [comment]
Also found this other one https://github.com/hashicorp/terraform/issues/26207

The module design seems very similar here with the root module passing the output of one module to another.

This one also fixed by the same merge https://github.com/hashicorp/terraform/issues/27849

**Comment by Nuru** [comment]
@paulrob-100 Thank you for your submission, we really appreciate it. However (@Gowiem please note) we have another submission, #46, which is a more complete solution, so we are going to focus on that. 

I greatly appreciate that you added tests. For future reference (and although you would not know it from just looking at this module), we only run tests in `us-east-2` for logistical reasons; please do not run tests elsewhere. We use [a random number attribute](https://github.com/cloudposse/terraform-example-module/blob/472d89f47a9af9aec2532dcef382193823be0ac8/test/src/examples_complete_test.go#L17-L19) so that we can run multiple test in the same region.

**Comment by paulrob-100** [comment]
Thank you for your review and work on #47 @Nuru. Much appreciated.

I noticed that the test I added in this PR hasn't been added to the #47 merge.
I'll take on board your guidance on us-east-2 testing and resubmit if still valuable.

**Pull request closed without merging**
