### PR TITLE
Removed deprecated template provider

### LINKED ISSUE #40: Module is unusable on Apple M1 Macs
hashicorp/template provider has been deprecated and so Hashicorp is not building ARM64 versions.

### PR DESCRIPTION
**Pull request by nadenf**
## what
* Removes references to the hashicorp/template provider which is deprecated.

## why
* So we can use module on M1 Macs.

## references
* closes #40

### CODE REVIEW

**Comment by Gowiem** [comment]
@nadenf could you run the following commands locally and commit:

```
make init
make readme
terraform fmt
```

We're having some problems with our CI on this repo for some reason.

**Comment by nadenf** [comment]
@Gowiem .. I don't see any checkbox to allow access. And when I run make/pr-autoformat the following error message:

```
Starting cloudposse/build-harness:slim-sha-bb66c2f
docker run --name build-harness \
		--rm -it \
		-e PACKAGES_PREFER_HOST=true \
		-e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e TERM -e AWS_PROFILE -e AWS_REGION -e AWS_DEFAULT_PROFILE -e AWS_DEFAULT_REGION -e AWS_CONFIG_FILE -e AWS_SHARED_CREDENTIALS_FILE \
		 \
		-v /Volumes/Docker/Developer/harana-oss/terraform-aws-multi-az-subnets:/opt \
		--workdir /opt \
		--entrypoint /usr/bin/make \
		cloudposse/build-harness:slim-sha-bb66c2f terraform/fmt readme
Unable to find image 'cloudposse/build-harness:slim-sha-bb66c2f' locally
docker: Error response from daemon: manifest for cloudposse/build-harness:slim-sha-bb66c2f not found: manifest unknown: manifest unknown.
See 'docker run --help'.
make: *** [build-harness/runner] Error 125
```

**Comment by Nuru** [comment]
@nadenf Sorry, you hit a bug in `build-harness` which is [now fixed](https://github.com/cloudposse/build-harness/pull/285). Please run
```
make init
make pr/auto-format
```
again

**Pull request closed without merging**
