### PR TITLE
Add ipv6 support

### LINKED ISSUE #43: Add Support for IPv6
## Describe the Feature

Support IPv6.

## Expected Behavior

IPv6 CIDRs should be allocated to the subnets.  Auto-assign IPv6 address should be enableable.

## Use Case

We need to assign IPv6 addresses to our VPC resources.  [cloudposse/terraform-aws-vpc](https://github.com/cloudposse/terraform-aws-vpc) already supports IPv6 so we just need to be able to assign to the subnets.

## Describe Ideal Solution

Allow for passing in `ipv6_cidr_block` and either assume that the addresses should be auto-assigned or provide an argument to toggle IPv6 auto-assignment and default to enabled if `ipv6_cidr_block` is present.

### PR DESCRIPTION
**Pull request by cdobbyn**
## what
* Add IPv6 subnet provisioning
* Assumes that the subnet created at the end must be a /64 (as per AWS).
* Only applies to public subnets. This could be added to private (with no default destination route `::/0`) if others think this is necessary. There is no concept of NAT in AWS VPC IPv6.

## why
* We have a requirement to offer dualstack workloads. 
* Today we have to do this manually and if using this module, separate subnets need to be created.

## references
* closes #43

### CODE REVIEW

**Comment by cdobbyn** [comment]
ping @srhopkins

**Comment by cdobbyn** [comment]
Ping @Gowiem. Only because you were interacting with someone in a previous PR and no one seems to be looking at this :/.

**Comment by bartelemi** [comment]
Any updates on this PR?

**Review by nitrocode — APPROVED** [review]
Looks good to me. @aknysh could you also review to double check ?

**Review by aknysh — APPROVED** [review]

**Comment by nitrocode** [comment]
Thanks @cdobbyn for your contribution, your persistence, and your patience!

**Pull request merged**
